from collections import OrderedDict
from collections.abc import Sequence
import numpy as np
from optionsfactory import WithMeta
from optionsfactory.checks import (
    is_non_negative,
    is_positive,
    NoneType,
)
from scipy.ndimage import zoom
try:
    from dipoleq_reader.read import DPEqFile
except ImportError:
    raise ImportWarning(
        "Missing optional dependency `dipoleq_reader`. Install it to use DPEqFile. https://github.com/openstarnz/DipoleEqReader "
    )
from ..core.equilibrium import Equilibrium, EquilibriumRegion, Point2D
from ..utils.utils import with_default
from ..utils import polygons

class DipoleEquilibrium(Equilibrium):
    """
    Magnetic configuration with concentric flux surfaces for a dipole

    Geometry based on the description of a dipole equilibrium generated by dipoleq (see )

    Can be either SOL-only with a limiter at the inboard midplane or core-only.
    """

    # Dipole-geometry-specific options and default values
    user_options_factory = Equilibrium.user_options_factory.add(
        limiter=WithMeta(
            False,
            doc=(
                "Core only, no limiter (False, default) or SOL only, with a limiter "
                "(True)"
            ),
            value_type=bool,
        ),
        nx=WithMeta(
            6,
            doc="Number of radial points (including boundary points)",
            value_type=int,
            check_all=is_positive,
        ),
        ny=WithMeta(
            8,
            doc="Number of poloidal points (excluding boundary points)",
            value_type=int,
            check_all=is_positive,
        ),
        R0=WithMeta(
            1.0,
            doc="Major radius of the magnetic axis",
            value_type=float,
            check_all=is_positive,
        ),

        r_inner=WithMeta(
            "fcfs",
            doc="Minor radius of the inner edge of the grid.",
            value_type=[float,str],
            #check_all=is_positive_str,
        ),
        r_outer=WithMeta(
            "lcfs",
            doc="Minor radius of the outer edge of the grid.",
            value_type=[float,str],
            #check_all=is_positive_str,
        ),
        psi_inner=WithMeta(
            None,
            doc=(
                "Unnormalised poloidal flux value at the core boundary, used in mesh "
                "generation. Overrides psinorm_core if this value is given, if the "
                "option is none, then calculated from psinorm_core"
            ),
            value_type=[float, int, NoneType, str],
        ),
        psi_outer=WithMeta(
            None,
            doc=(
                "Unnormalised poloidal flux value at the SOL boundary, used in mesh "
                "generation. Overrides psinorm_sol if this value is given, if the "
                "option is none, then calculated from psinorm_sol"
            ),
            value_type=[float, int, str, NoneType],
        ),
        initial_point = WithMeta(
            "imp",
            doc=(
                "location of initial point for contour following"

            ),
            value_type=[str],
        ),
        alpha_ref = WithMeta(
            0.5,
            doc=(
                "location of contour for point distribution"
            ),
            value_type=[float],
        ),
    )

    def __init__(self, wall=None, settings=None, nonorthogonal_settings=None):
        """
        Create a dipole flux surface geometry

        Parameters
        ----------
        settings : dict
            A dict that will be used to set non-default values of options
            (self.user_options)
        """
        if settings is None:
            settings = {}
        if nonorthogonal_settings is None:
            nonorthogonal_settings = {}

        self.user_options = self.user_options_factory.create(settings)


        super().__init__(nonorthogonal_settings)


        print(self.user_options.as_table(), flush=True)
        if not self.user_options.orthogonal:
            print(self.nonorthogonal_options.as_table(), flush=True)




            # load a dpeq-file

        dpeq = DPEqFile(settings["dpeqfile"])
        R = dpeq.get_r(transpose=False, zoom_factor=1)
        Z = dpeq.get_z(transpose=False, zoom_factor=1)
        twopi = 2 * np.pi
        psirz = dpeq.get_psirz(transpose=True, zoom_factor=1)
        self.dpeq = dpeq
        wall = dpeq.get_outerwall(format='r-z')
        wall = np.array([(r, z) for r, z in zip(wall[0], wall[1])])

        self.makeWall(wall)
        # Bounding box for domain
        self.Rmin = dpeq.get_rmin()
        self.Rmax = dpeq.get_rmax()
        self.Zmin = dpeq.get_zmin()
        self.Zmax = dpeq.get_zmax()

        self.psi_inner = with_default(
            self.user_options.psi_inner, dpeq.get_psi_rmp(self.user_options.r_inner)
        )
        if type(self.psi_inner) is str:
            if self.psi_inner == "peak":
                self.psi_inner = dpeq.get_psi_peak()
            elif self.psi_inner == "fcfs":
                self.psi_inner = dpeq.get_psi_fcfs(self.user_options.r_inner)
            else:
                raise ValueError(f"Invalid value for psi_inner: {self.psi_inner}. Choose 'peak' or 'fcfs' or give a float.")
        
        self.psi_outer = with_default(
            self.user_options.psi_outer,dpeq.get_psi_rmp(self.user_options.r_outer)
        )
        if type(self.psi_outer) is str:
            if self.psi_outer == "peak":
                self.psi_outer = dpeq.get_psi_peak()
            elif self.psi_outer == "lcfs":
                self.psi_outer = dpeq.get_psi_lcfs(self.user_options.r_outer)
            else:
                raise ValueError(f"Invalid value for psi_outer: {self.psi_outer}. Choose 'peak' or 'lcfs' or give a float.")
        

        print("-- psi_inner", self.psi_inner)
        print("-- psi_outer", self.psi_outer)

        self.magneticFunctionsFromGrid(
            R, Z, psirz, self.user_options.psi_interpolation_method
        )

        self.regions = OrderedDict(dipole=self.makeRegion())
        self.poloidal_spacing_delta_psi = with_default(
            self.user_options.poloidal_spacing_delta_psi,
            np.abs(
                (
                        self.psi_inner
                        - self.psi_outer
                )
                / 20.0
            ),
        )
        self.Bt_axis = 0.0
        if self.user_options.limiter:
            self.psi_sep = [self.psi_inner]
        else:
            self.psi_sep = [self.psi_outer]

            # Core-only geometry: add connection so domain is periodic in y
            self.makeConnection("dipole", 0, "dipole", 0)

    # psi values
    def _psinorm_to_psi(self, psinorm):
        if psinorm is None:
            return None
        return self.psi_axis + psinorm * (self.psi_sep[0] - self.psi_axis)

    def _psi_to_psinorm(self, psi):
        if psi is None:
            return None
        return (psi - self.psi_axis) / (self.psi_sep[0] - self.psi_axis)
    def fpol(self, psi):
        """poloidal current function, returns fpol such that B_toroidal = fpol/R"""
        return 0.0

    def fpolprime(self, psi):
        """psi-derivative of fpol"""
        return 0.0

    def makeWall(self, wall):
        # Wall geometry. Note: should be anti-clockwise
        if wall is None:
            # No wall given, so add one which is just inside the domain edge
            offset = 1e-2  # in m
            wall = [
                (self.Rmin + offset, self.Zmin + offset),
                (self.Rmax - offset, self.Zmin + offset),
                (self.Rmax - offset, self.Zmax - offset),
                (self.Rmin + offset, self.Zmax - offset),
            ]
        elif len(wall) < 3:
            raise ValueError(
                f"Wall must be a polygon, so should have at least 3 points. Got "
                f"wall={wall}"
            )
        print(wall)
        if polygons.clockwise(wall):
            wall = wall[
                ::-1
            ]  # Reverse, without modifying input list (which .reverse() would)
        self.wall = [Point2D(r, z) for r, z in wall]
        # Create numpy array with closed set of points for wall, avoids repeating
        # this operation
        closed_wall = self.wall + [self.wall[0]]
        self.closed_wallarray = np.array([(p.R, p.Z) for p in closed_wall])


    def makeRegion(self):
        """
        Create the EquilibriumRegion to build the grid around
        """

        if self.user_options.limiter:
            kind = "wall.wall"
        else:
            # No actual 'X-point' in this dipole geometry, but this 'kind' will create
            # a y-periodic region -> core region with no limiter
            kind = "X.X"

        n_points = 1000
        #thetas = np.linspace(np.pi, -np.pi, n_points)
        #R0 = self.user_options.R0
        #points = [
        #    Point2D(R0 + r0 * np.cos(theta), r0 * np.sin(theta)) for theta in thetas
        #]
        alpha_ref = self.user_options.alpha_ref
        initial_point = self.user_options.initial_point
        # we take the contour of psi at the value corresponding to r0 as the line to build the region around, so that the grid is more aligned with the flux surfaces
        points = [Point2D(x,y) for (x,y) in self.dpeq.get_psi_contour((self.psi_inner*alpha_ref + (1-alpha_ref)*self.psi_outer), n_points=n_points, rotate=initial_point, closed=False)[0]]



        eq_reg = EquilibriumRegion(
            equilibrium=self,
            name="dipole",
            nSegments=1,  # The number of radial regions
            nx=[self.user_options.nx],
            ny=self.user_options.ny,
            ny_total=self.user_options.ny,
            kind=kind,
            # The following arguments are passed through to PsiContour
            points=points,  # list of Point2D objects on the line
            psival=self.psi_inner,
            Rrange=(self.Rmin   , self.Rmax),
            Zrange=(-float("inf"), float("inf")),
        )

        eq_reg.psi_vals = [
            np.linspace(
                self.psi_inner,
                self.psi_outer,
                2 * self.user_options.nx + 1,
            )
        ]

        if self.user_options.limiter:
            eq_reg.separatrix_radial_index = 0
        else:
            eq_reg.separatrix_radial_index = -1

        return eq_reg

