# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  [push, pull_request]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest


  integrated-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Integrated tests
      run: |
        pip install pytest xarray
        cd integrated_tests/
        ./test_suite.py


  examples:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy
        pip install -e .
    - name: Examples
      run: |
        cd examples/tokamak
        ./tokamak_example.py --no-plot lsn
        ./tokamak_example.py --no-plot usn
        ./tokamak_example.py --no-plot cdn
        ./tokamak_example.py --no-plot ldn
        ./tokamak_example.py --no-plot udn
        ./tokamak_example.py --no-plot udn2
        cd ../torpex-xpoint
        hypnotoad_torpex --noplot torpex-coils.yaml
        hypnotoad_torpex --noplot torpex-coils-nonorth.yaml


  flake8:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8


  black:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check formatting with black
      run: |
        pip install black
        black --check --diff --color .
