# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check version number for release (version number should be more recent than latest tag)

on:
  push:
    branches: [ releases ]
  pull_request:
    branches: [ releases ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython
    - name: Check version number for release (version number should be more recent than latest tag)
      run: |
        test $(python3 -c "from hypnotoad2.__version__ import __version__; from git import Repo; from packaging import version; result = version.parse(__version__) > version.parse(Repo('.').git.describe('--tags', '--abbrev=0', 'releases')); print(result)") = True
